apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: kanishk2207/patient_service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: patient-service-secret
              key: dsn
        - name: HTTPADDRESS
          valueFrom:
            configMapKeyRef:
              name: patient-service-config
              key: HTTPAddress
        - name: GRPCADDRESS
          valueFrom:
            configMapKeyRef:
              name: patient-service-config
              key: GRPCAddress
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: patient-service-secret
              key: JWTSECRET
        - name: JWTEXPIRY
          valueFrom:
            secretKeyRef:
              name: patient-service-secret
              key: JWTEXPIRY
